- src/app/paginas/templates/footer/footer.component.html
The footbar has been changed to: "About us", "Contact us" and "Cite us" instead of "Facebook link" and "Login as Admin"
> Footbar changes

- src/app/app-routing.module.ts
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/19
> Fix typo in URL

- src/app/paginas/templates/footer/footer.component.html
- src/app/paginas/templates/header/header.component.html
Replace
> Cell Recognition For Inspection Of Cervix
with
> Center for Recognition and Inspection of Cells
> Fix CRIC name

- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/39
> Add argument to cadastrarSegmentacaoElementoAnucleado()

- src/app/api_cric_database/comunicacao_api.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/34.
> Use environment-specific variables for UrlBaseApi

- src/app/paginas/templates/footer/footer.component.html
- src/app/paginas/templates/footer/footer.component.ts
- src/app/utils/links_externos.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/2
> Improve list of universities at foot bar

- src/app/paginas/templates/footer/footer.component.html
- src/app/paginas/templates/footer/footer.component.ts
- src/app/utils/links_externos.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/3
> Improve links about CRIC at foot bar

- src/app/paginas/about/about.component.html
> Add Cite us into About

- src/app/paginas/templates/footer/footer.component.ts
- src/app/utils/links_externos.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/16
> Fix typo in foot

- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/app/paginas/classification-database/classification-database.component.ts
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
- src/app/paginas/segmentation-database/segmentation-database.component.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/76
> Make property objetoSessao public

- src/app/paginas/privacy/privacy.component.html
> Add Privacy Policy generated with https://getterms.io

- src/app/paginas/terms/terms.component.html
> Add Terms & Conditions generated with https://getterms.io

- src/app/components/login/login.component.html
- src/app/components/login/login.component.ts
- src/app/services/login/autenticacao.service.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/88
> Improve response to user when login fail

- src/app/app.module.ts
- src/app/components/imagem/image-info/image-info.component.html
- src/app/components/imagem/image-info/image-info.component.scss
- src/app/components/imagem/image-info/image-info.component.spec.ts
- src/app/components/imagem/image-info/image-info.component.ts
- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.html
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.scss
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
- src/app/paginas/segmentation-database/segmentation-database.component.html
- src/assets/javaScript/canvas.js
- Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/20
- Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/21
> Improve segmentation

- Dockerfile
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/42
> Fix Dockerfile rule for production image

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/74
> Handle correct return of /api/v1/imagens/{image_id}/classificacao-celula/{user_id}

- src/app/components/login/login.component.html
- src/app/components/login/login.component.ts
- src/app/services/usuarios/usuarios.service.ts
> Add support to forgot password to component

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.html
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
- src/app/components/login/login.component.html
- src/app/components/sistema/cite-us/cite-us.component.html
- src/app/paginas/templates/footer/footer.component.ts
- src/app/paginas/upload-image/upload-image.component.html
- src/app/paginas/upload-image/upload-image.component.spec.ts
- src/app/paginas/upload-image/upload-image.component.ts
> Add filter

- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
Based on https://github.com/angular/angular/issues/6595#issuecomment-519705192.
> Fix issue of not scroll to dashboard

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/assets/javaScript/canvas.js
- src/sass/styles.scss
Fix problem that right click -> save image as ... will only provide the canvas and not the background.
> Allow user to download visible canvas

- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/111
> Fix card list when filter return zero cards

- src/app/admin/user/user.component.html
- src/app/admin/user/user.component.spec.ts
- src/app/admin/user/user.component.ts
- src/app/app-routing.module.ts
- src/app/paginas/templates/header/header.component.html
- src/app/paginas/usuario/usuario.component.html
- src/app/paginas/usuario/usuario.component.ts
> Add page for user private collection

- src/app/paginas/upload-image/upload-image.component.html
- src/app/paginas/upload-image/upload-image.component.ts
> Remove injury field from upload page

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
> Add button to download JSON and CSV for individual image

- src/app/app.module.ts
To avoid deep imports.
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/120
> Remove angular-highcharts

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/assets/javaScript/canvas.js
> Add Disable label to classification

- src/app/components/header/header.component.html
- src/app/paginas/downloads/downloads.component.html
- src/app/paginas/downloads/downloads.component.ts
- src/app/services/imagens_service/imagens.service.ts
> Add form to custom download

- src/app/app.module.ts
- src/app/components/header/header.component.html
- src/app/components/header/header.component.ts
- src/app/models/autenticacao/objeto_sessao.model.ts
- src/app/models/usuario/usuario_completo.model.ts
- src/app/services/login/autenticacao.service.ts
- src/app/user/classfication-database/user-classification-database.component.html
- src/app/user/home/user-home.component.html
- src/app/user/nav/user-nav.component.html
- src/app/user/nav/user-nav.component.spec.ts
- src/app/user/nav/user-nav.component.ts
> Improve User Panel

- src/app/paginas/upload-image/upload-image.component.html
- src/app/paginas/upload-image/upload-image.component.ts
- Use loader in button
- Correct URL to segmantation and classification
> Improve upload page

- src/app/admin/home/admin-home.component.html
- src/app/admin/injury/admin-injury.component.html
- src/app/admin/injury/admin-injury.component.spec.ts
- src/app/admin/injury/admin-injury.component.ts
- src/app/admin/routing.ts
- src/app/admin/user/admin-user.component.html
- src/app/admin/user/admin-user.component.ts
- src/app/app.module.ts
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
- src/app/models/imagem/lesao.model.ts
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/app/paginas/classification-database/classification-database.component.ts
- src/app/paginas/downloads/downloads.component.ts
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
- src/app/paginas/segmentation-database/segmentation-database.component.ts
- src/app/paginas/upload-image/upload-image.component.ts
- src/app/services/imagens.service.ts
- src/app/user/classfication-database/user-classification-database.component.ts
> Edit injury

- src/app/admin/user/admin-user.component.html
- src/app/components/login/login.component.html
This is what figshare uses,
see https://docs.figshare.com/#private_author_details.
> Use "First name" and "Last name"

- src/app/user/home/user-home.component.html
> Disable user segmentation

- src/app/components/login/login.component.html
- src/app/components/login/login.component.ts
- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/app/paginas/classification-database/classification-database.component.html
- src/app/paginas/classification-database/classification-database.component.ts
- src/app/paginas/downloads/downloads.component.html
- src/app/paginas/downloads/downloads.component.ts
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.html
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
- src/app/paginas/segmentation-database/segmentation-database.component.html
- src/app/paginas/segmentation-database/segmentation-database.component.ts
- src/app/paginas/upload-image/upload-image.component.html
- src/app/paginas/upload-image/upload-image.component.ts
- src/environments/environment.ts
Requires https://github.com/CRICDatabase/searchable-image-database/commit/f2bbffe2b1f2f511a03e5fdc3a000cb6e47592df
> Add more alert boxes related with playground

- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.html
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
> Improve card filter

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/sass/styles.scss
> Improve user feedback in classification canvas

- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.html
> Add trash icon to image card

- src/app/paginas/downloads/downloads.component.html
- src/app/paginas/downloads/downloads.component.ts
> Allow log in user to download segmentation

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
> Provide feedback to user if no cell recorded

- src/app/paginas/upload-image/upload-image.component.html
- src/app/paginas/upload-image/upload-image.component.ts
> Add button to upload another image

- src/app/admin/injury/admin-injury.component.ts
- src/app/admin/user/admin-user.component.ts
- src/app/components/header/header.component.ts
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.ts
- src/app/components/imagem/listar-cards-imagem/pagina_imagem.entidede.ts
- src/app/components/usuario/cadastro-visitante/cadastro-visitante.component.ts
- src/app/models/imagem/imagem.model.ts
- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/app/paginas/classification-database/classification-database.component.ts
- src/app/paginas/downloads/downloads.component.ts
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
- src/app/paginas/segmentation-database/segmentation-database.component.ts
- src/app/paginas/upload-image/upload-image.component.ts
- src/app/services/imagens.service.ts
- src/app/user/classfication-database/user-classification-database.component.ts
- src/app/utils/tratamento_erro/ObjetoErro.ts
**Note**: the button doesn't work because backend is missing implementation.
> Add button to delete image

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/183
Before
After
> Fix style for button

- custom-webpack.config.js
Close https://github.com/CRICDatabase/searchable-image-database-angular/issues/180
> Fix contact details

- src/app/components/header/header.component.html
- src/app/components/header/header.component.scss
close https://github.com/CRICDatabase/searchable-image-database-angular/issues/186
> fix header não alinhado

- src/app/components/header/header.component.html
- src/app/components/header/header.component.scss
- src/app/components/imagem/listar-cards-imagem/listar-cards-imagem.component.html
close https://github.com/CRICDatabase/searchable-image-database-angular/issues/188
> Fix responsive cervix collection

- src/app/components/footer/footer.component.html
- src/app/paginas/downloads/downloads.component.html
- src/app/paginas/index/index.component.scss
- src/app/user/home/user-home.component.scss
> Updating footer and download information

- src/app/paginas/classificar-imagem/classificar-imagem.component.html
- src/app/paginas/classificar-imagem/classificar-imagem.component.ts
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.html
- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
> Delete segmented image and .CSV and .JSON export implemented

- src/app/paginas/segmentar-imagem/segmentar-imagem.component.ts
- src/app/services/imagens.service.ts
> Delete segmentation fixed

- src/app/components/login/login.component.html
- src/app/paginas/about/about.component.html
- src/app/paginas/downloads/downloads.component.html
Adapting the database for what users can do or not.
"Forgot password" button and dynamic download info commented.
"Sign up" button altered with a playground condiiton.
> Adapt Database

- src/app/components/footer/footer.component.scss
- src/app/components/header/header.component.scss
- src/app/paginas/downloads/downloads.component.html
- src/app/paginas/index/index.component.html
- src/app/paginas/index/index.component.scss
> Add article and video tutorial to home page
